trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Checkout code
  - checkout: self

  # Step 2: Set up Python
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'

  # Step 3: Install dependencies
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  # Step 4: Run tests
  - script: |
      pytest --maxfail=5 --disable-warnings -q
    displayName: 'Run tests'

  # Step 5: Publish test results
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/test-results.xml'
      failTaskOnFailedTests: true
